### PR TITLE
Keep pyx12.version in sync with package version.

### PR DESCRIPTION
**Pull request by jdavisp3**
This PR makes `setup.py` use the version number in `pyx12.version` so they stay in sync and updates `pyx12.version` to be `2.2.0`.

### CODE REVIEW

**Comment by azoner** [comment]
There does not seem to be a canonical way to solve this.  I seem to remember an install edge case where the method of reading the version from the package fails.

http://stackoverflow.com/questions/17583443/what-is-the-correct-way-to-share-package-version-with-setup-py-and-the-package

For now, I'd just prefer to manually keep them in sync.

**Comment by jdavisp3** [comment]
Ok, sounds good. Did you mean to merge this? My reading of that stackoverflow answer is that the method in this PR will work since no third-party library is needed to import `pyx12.version`, FYI.

**Comment by azoner** [comment]
Yes.  I wanted to add the history.  I just reverted the change to setup.py.

The case I want to test is a new install of pyx12.  Will pip / setup_tools have access to pyx12.__version__ before the package is installed?

**Comment by jdavisp3** [comment]
Cool. FYI, this is how my company sets up our internal packages, packaged and deployed with pip. Also, django does [something similar](https://github.com/django/django/blob/master/setup.py) so I think this method is at least standard-ish and works in general.

**Pull request merged**
